version: 2
updates:
  # Enable version updates for npm
  - package-ecosystem: 'npm'
    # Look for `package.json` and `lock` files in the `root` directory
    directory: '/'
    # Check the npm registry for updates weekly
    schedule:
      interval: 'weekly'
    commit-message:
      prefix: "deps(npm): "
    labels:
      - "dependencies"
    # ignore all patch level updates
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-patch"]
  # Enable version updates for github-actions
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      # Check for updates to GitHub Actions once a month
      interval: 'weekly'
    commit-message:
      prefix: "deps(github-actions): "
    labels:
      - "gha-workflow"  
